### ISSUE TITLE
Any thoughts around adding multi-root support?

### ISSUE THREAD

**Issue by lukebatchelor** [wangtao0101/vscode-js-import#1]
This is an AWESOME addon!

I noticed in your readme you have 

```
//the source dir, currently we only support single root
"js-import.root": "src"
```

Just wondering if you had any plans for adding multi-root support? This would be fantastic for [lerna](https://github.com/lerna/lerna) style mono-repos for example, or [yarn workspaces](https://github.com/yarnpkg/yarn/issues/3294) (when they land).

**Comment by wangtao0101** [comment]
@lukebatchelor actually, the extension support multiple package like lerna style if all packages are in src, just see config js-import.alias.
