### ISSUE TITLE
Open to remove leading ./ if is ./../

### ISSUE THREAD

**Issue by Noitidart** [wangtao0101/vscode-js-import#11]
Hi there,

Is there an option to remove the leading `./` if the next one is a double dot `../`?

Thanksfor this competition vs Auto Import with 250k users, I like this one more.

**Comment by wangtao0101** [comment]
@Noitidart Thank you, I have fix the bug and release new version

**Comment by Noitidart** [comment]
Oh wow thank you very much sir!!
