### ISSUE TITLE
Having EMFILE error with a large repo

### ISSUE THREAD

**Issue by aifreedom** [wangtao0101/vscode-js-import#13]
Hi @wangtao0101 , thank you for making this extension! 

I have trouble using it in a big repo with about 16k js/jsx files. Pressing "Cmd + Opt + H" shows the error `Running the contributed command:'extension.shortcutImport' failed.`. In vscode's debug console, there are many errors like `[Extension Host] Error: EMFILE: too many open files, open /xxx/yyy/zzz.js`.

Can you take a look?

Thanks!

**Comment by wangtao0101** [comment]
@aifreedom Maybe the default limit file is 10480, you can have a try :
```
ulimit -n 20960 \\or
ulimit -n 41920
```
If it doesn't work, I will try to fix this by code.
