### ISSUE TITLE
Type variable, then use shortcut it erases variable

### ISSUE THREAD

**Issue by Noitidart** [wangtao0101/vscode-js-import#14]
If I type the variable, then hit the shortcut to open pane (i like this method as its faster then waiting for dropdown to show), then select import it erases variable. Here is screencast:

HD: https://gfycat.com/DisfiguredWavyAnhinga

gif: 

![](https://thumbs.gfycat.com/DisfiguredWavyAnhinga-small.gif)

**Comment by wangtao0101** [comment]
@Noitidart I do this on purpose. If the word is the only word in the line, it will erases the variable after import...Should I change it ?

**Comment by Noitidart** [comment]
Oh interesting. I never actually found a use for that. Do you find that useful? Thanks for asking for my input! I always thought it was a bug for this long haha.

**Comment by wangtao0101** [comment]
@Noitidart I think i will remove the bug. I actually unuseful. Thank you.

**Comment by Noitidart** [comment]
Thank you very much!!
