### ISSUE TITLE
It doesn't work when module has decorators

### ISSUE THREAD

**Issue by jansav** [wangtao0101/vscode-js-import#19]
Hi

I'm working on with project that uses React and MobX. That being said, some of our components have observer decorators which breaks auto import mechanic.

Eg.

***ComponentWithoutMobx.js***
```
function ComponentWithoutMobx() {
  return (
    <div>
      This is some component without MobX decorators. This can be imported fine.
    </div>
  );
}

export default ComponentWithoutMobx;
```

***ComponentWithMobxObserverDecorator.js***
```
import { observer } from 'mobx-react';

function ComponentWithMobxObserverDecorator() {
  return (
    <div>
      This component has MobX observer decorator which means that it cannot be
      imported automatically anymore
    </div>
  );
}

export default observer(ComponentWithMobxObserverDecorator);
```

***TestComponent.js***
```
function TestComponent() {
  return (
    <div>
      <ComponentWithoutMobx />

      <ComponentWithMobxObserverDecorator />
    </div>
  );
}

export default TestComponent;
```

When I'm trying to use components, I expect to be able to import both of these automatically. However, ComponentWithoutMobx works fine and ComponentWithMobxObserverDecorator doesn't.

Plugin version: 0.15.4
VSCode: 1.23.0

**Comment by wangtao0101** [comment]
```
export default observer(ComponentWithMobxObserverDecorator);
```
Above export statement is not export ComponentWithMobxObserverDecorator, but export observer(ComponentWithMobxObserverDecorator). The extension is hard to solve this situation.

I suggest you can change your code to this:
```
import { observer } from 'mobx-react';

function ComponentWithMobxObserver() {
  return (
    <div>
      This component has MobX observer decorator which means that it cannot be
      imported automatically anymore
    </div>
  );
}

const ComponentWithMobxObserverDecorator = observer(ComponentWithMobxObserver);
export default ComponentWithMobxObserverDecorator;
```

**Comment by jansav** [comment]
This is something that every other auto import -extensions that I have used (within multiple IDEs) has solved. 

At least this package for Atom works fine: https://github.com/galooshi/atom-import-js

But anyway, thanks for the suggestion.

**Comment by wangtao0101** [comment]
In the extension i also use import-js to help find import only in node_module. But actually `export default observer(ComponentWithMobxObserverDecorator);` is not a stardard export, it is anonymous. Maybe next major i will support it.
