### ISSUE TITLE
unable to import via non-relative path from baseUrl

### ISSUE THREAD

**Issue by rlarner-quizlet** [wangtao0101/vscode-js-import#20]
First off, thanks for the great extension! I am trying to figure out how to get the imports generated by the extension to not be relative, instead I want them to start from the `baseUrl`. For instance, there's a function `bar` defined in `app/j/foo.js`. When I try to import bar from . `app/j/component/baz.js` I would like the import to look like:
```
import { bar } from 'foo';
```
Instead, what I am getting is:
```
import { bar } from '../foo';
```
I have created a file `jsconfig.json`  in `app/j` with this content:
```
{
  "compilerOptions": {
    "target": "es6"
  }
}
```

What am I missing?

**Comment by wangtao0101** [comment]
If you want to get non-relative path, you should use lerna style. Then one package import other package the path will be absolute. You can see config: alias.
