### ISSUE TITLE
Support import from node_module modules?

### ISSUE THREAD

**Issue by Lxxyx** [wangtao0101/vscode-js-import#3]
Like this:

```
import React from 'react'
import { Grid } from 'react-bootstrap'
```

And when type Grid, auto suggest import { Grid } from 'react-bootstrap'.

**Comment by wangtao0101** [comment]
@Lxxyx Actually the extension support node_module module with limitation. But, I have test react and react-bootstrap, it's work.
See https://github.com/wangtao0101/vscode-js-import#node_modules-support
Can this help you ?

**Comment by Lxxyx** [comment]
Yes, Thank you.
