### ISSUE TITLE
Great utility, just have a question on how to exclude PropTypes from react?

### ISSUE THREAD

**Issue by oshalygin** [wangtao0101/vscode-js-import#4]
With the latest versions of React, `{PropTypes} from 'react'` is deprecated and should be pulled from the `prop-types` package, eg: `import PropTypes from 'prop-types'`.

Any ideas on how to get around this?  I didn't see any of the config options that could address this?

Willing to help as well 👍

**Comment by wangtao0101** [comment]
@oshalygin Handle deprecated package is difficult for this extension. And I think how to import PropTypes from 'prop-types' is more useful. Actually you can add prop-types in package.json, so the extension will find  two packages of 'PropTypes'. (be care of the version of prop-types when you install 'prop-types'). See config [node_modules-support](https://github.com/wangtao0101/vscode-js-import#node_modules-support)
Can this help you ?

**Comment by oshalygin** [comment]
Yep this helps thanks so much!
