### ISSUE TITLE
Refresh exports to use those for imports

### ISSUE THREAD

**Issue by astrauka** [wangtao0101/vscode-js-import#6]
Hey :) Thank you for working on this great plugin - love it!
What I find annoying - I create an export, e.g.
```
export NEW_CONST = 'x';
```
and then want to use it. Sadly, the new export cannot be found among the imports list.
If I reopen vscode or change project forth and back, then the export appears among suggestions.
It would be great to provide a shortcut to re-scan the code for new exports.
What do you think @wangtao0101 ?

**Comment by wangtao0101** [comment]
@astrauka actually the extension will watch file create, change and then (after enter ctrl + s) rescan the exports, and i have test 
the export 'export NEW_CONST = 'x';', in my vscode i can get the NEW_CONST  in imports list. Can you test once more?

**Comment by wangtao0101** [comment]
@astrauka  can this help you ?

**Comment by astrauka** [comment]
@wangtao0101 it works, thank you for checking it :)
