### ISSUE TITLE
Allow us to define our custom import statement formatter or parse the `.importjs.js` file.

### ISSUE THREAD

**Issue by elboletaire** [wangtao0101/vscode-js-import#7]
I don't use semi when writing javascript code, but this plugin always add the semi to the end of the import line.

AFAIK, the `import.js` accepts an `.importjs.js` file where you can set custom options. I'd like to define the `importStatementFormatter`, so I can manually remove that semi from the lineending. 

Using `import.js` I'd create an `.importjs.js` file containing the following:

~~~javascript
module.exports = {
  importStatementFormatter({ importStatement }) {
    return importStatement.replace(/;$/, '');
  }
}
~~~

This works with `import.js`, but not with this plugin. Any way to allow me to change the statement format would be welcome! 😄

**Comment by wangtao0101** [comment]
@elboletaire I will add a importStatementFormatter option for this requirement.

**Comment by wangtao0101** [comment]
@elboletaire I have released a new version. You can check the config of js-import.semicolon.
